### ISSUE TITLE
how to add some persistence storage ?

### ISSUE THREAD

**Issue by arm2arm** [sagemathinc/cocalc-kubernetes#7]
how to add some persistence storage ?

**Comment by williamstein** [comment]
As mentioned at https://github.com/sagemathinc/cocalc-kubernetes/tree/master/server
you have to edit server/deployment.yaml so that the `projects` volume isn't ephemeral.

You can see [here](https://github.com/sagemathinc/cocalc-kubernetes/blob/master/server/deployment.yaml#L49) that right now the volume is ephemeral.  How you actually make it persistent is not specific to colcalc-kubernetes, and depends entirely on you knowing Kubernetes in general and on the specific Kubernetes platform you are using.  Look up things like "persistent volumes", "persistent volume claims", etc...
